version: "3"
services:
  mongo:
    image: mongo:5
    container_name: mongo-amaiie
    restart: always
    environment:
      MONGO_INITDB_DATABASE: amaiie
    volumes:
      - ~/amaiieData/mongo:/data/db
    networks:
      - amaiie
  node:
    build: .
    container_name: node-amaiie
    restart: always
    expose:
      - "5000"
    depends_on:
      - mongo
    networks:
      - amaiie
      - proxy
    volumes:
      - ./:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    environment:
      - VIRTUAL_HOST=api.amaiie.lafuentedanel.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.amaiie.lafuentedanel.com
      - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
  react:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=amaiie.lafuentedanel.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=amaiie.lafuentedanel.com
      - LETSENCRYPT_EMAIL=admin@lafuentedanel.com
    volumes:
      - /home/ubuntu/amaiie:/usr/share/nginx/html:ro
    networks:
      - proxy
    restart: unless-stopped

volumes:
  exclude:
networks:
  amaiie:
  proxy:
    external:
      name: nginx-proxy
